title: Blake Matthews
intro:

# Avatar must be uploaded to theme "img" folder.
intro_avatar:
author:
  name: Blake Matthews
  email: 'test@test.com'
  footer:
  footer2: <b>© 2019 Blake Matthews</b> · Group Leader · Department Fish Ecology & Evolution · <b> EAWAG </b> Swiss Federal Institute of Freshwater Science and Technology
  url: https://www.eawag.ch/
  url2:
metadata:
    description:

# Main Menu
menu:
  - text:
    link:

social:
  - icon:
    link:
  - icon:
    link:
  - icon:
    link:
  - icon:
    link:
